osx_image: xcode8.1

dist: trusty
sudo: required

language: c

matrix:
  include:
    - os: osx
    - os: linux
      compiler: gcc

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils
      - graphicsmagick
      - xz-utils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export CXX="g++-4.8" CC="gcc-4.8";
    sudo add-apt-repository ppa:ubuntu-wine/ppa -y;
    sudo dpkg --add-architecture i386;
    sudo apt-get update;
    sudo apt-get install --no-install-recommends -y wine1.8;
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
    echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list;
    sudo apt-get update;
    sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono;
    fi

install:
- nvm install 7
- yarn install

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  yarn run dist:win;
  yarn run dist:linux;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  yarn run dist:osx;
  fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"